apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: joelongtoe/f23-ex2:sleep
    env:
    - name: BOOK
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: BOOK
    - name: MOVIE
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: MOVIE
    - name: BAND
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: BAND
    - name: ANIMAL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: ANIMAL